;=====================References Used:========================
; 1. Archived Mobile Configs by AlteriaX 	(https://github.com/AlteriaX/WuWa-Configs-Android/tree/main)
; 2. UE Official CVar Reference 	(https://dev.epicgames.com/documentation/en-us/unreal-engine/unreal-engine-console-variables-reference)
; ============================================================
; note from orpheus: this device profile is a work in progress, further testing is needed
; credit to arglax and daisuke-19 for the CVars codes
; ====================END OF MAIN NOTES=======================

[Android_Lowest DeviceProfile] ; replace the "lowest" with your device profile
BaseProfileName=Galbrena
DeviceScore=5000

[Galbrena DeviceProfile] 
Cvars=r.Mobile.HighQualityMaterial=0 ; 1 for better graphics
Cvars=wp.Runtime.LoadingRangeScale=0.80
CVars=sg.ViewDistanceQuality=0
CVars=sg.AntiAliasingQuality=0
CVars=sg.ShadowQuality=0
CVars=sg.PostProcessQuality=0
CVars=sg.TextureQuality=0
CVars=sg.EffectsQuality=0
CVars=sg.FoliageQuality=0
CVars=sg.ShadingQuality=0
CVars=wp.Runtime.LoadingRangeScale=0.20
CVars=wp.Runtime.PlannedLoadingRangeScale=0.50
CVars=a.URO.Enable=1
CVars=a.URO.ForceAnimRate=3 ; set to 2 if chars feel weird for u
CVars=a.URO.ForceInterpolation=1
Cvars=wp.Runtime.LoadingRangeScale=1.0
CVars=r.Kuro.OverallPerformancePriority.Aggressive=2
CVars=r.Kuro.ScenePerformancePriority.Aggressive=2
CVars=r.Kuro.CombatPerformancePriority.Aggressive=2
CVars=r.Android.DisableVulkanSupport=0
CVars=r.Kuro.MaterialMobileQualityShoulderRender=0
CVars=FrameRateLock=60
CVars=bEnableDynamicMaxFPS=True
CVars=a.UseSwappyForFramePacing=1
CVars=bSupportsVulkan=True
CVars=bSupportsVulkanSM5=True
Cvars=rhi.SyncInterval=0
Cvars=r.FramePace=60
Cvars=t.MaxFPS=60
Cvars=t.OverrideFPS=60
Cvars=MinDesiredFrameRate=20.000000
Cvars=MaxDesiredFrameRate=60.000000
Cvars=FrameRateLimit=60.000000

CVars=r.Streaming.PoolSize=5120
CVars=r.Streaming.MipBias=0
CVars=r.Streaming.LimitPoolSizeToVRAM=1
CVars=s.AsyncLoadingThreadEnabled=1
CVars=s.AsyncPipeline=1
CVars=r.Mobile.EarlyZPass=1
