; ============================================================
; Potato Config Link: https://github.com/Arglax/Mobile-WuWa-Config/tree/main/%5BV3.x%5D%20Working%20Configs/Potato%20Config
;_____________________________________________________________
; July 14, 2026
; ============================================================
; 			Final Notes
; Potato Config with High-Quality Material (SG groups zeroed)
; If this doesn't work for you, check out CVW's discord
;	Config Main Repository: https://github.com/Arglax/Mobile-WuWa-Config/
; ============================================================
; 			References Used:
; 1. Archived Mobile Configs by AlteriaX 	(https://github.com/AlteriaX/WuWa-Configs-Android/tree/main)
; 2. UE Official CVar Reference 	(https://dev.epicgames.com/documentation/en-us/unreal-engine/unreal-engine-console-variables-reference)
; ====================END OF MAIN NOTES=======================

[Android_Lowest DeviceProfile]
DeviceScore=6969
Cvars=r.Mobile.HighQualityMaterial=0  ;1 for better graphics
Cvars=wp.Runtime.LoadingRangeScale=0.80
CVars=sg.ViewDistanceQuality=0
CVars=sg.AntiAliasingQuality=0
CVars=sg.ShadowQuality=0
CVars=sg.PostProcessQuality=0
CVars=sg.TextureQuality=0
CVars=sg.EffectsQuality=0
CVars=sg.FoliageQuality=0
CVars=sg.ShadingQuality=0
CVars=wp.Runtime.LoadingRangeScale=0.20
CVars=wp.Runtime.PlannedLoadingRangeScale=0.50
CVars=a.URO.Enable=1
CVars=a.URO.ForceAnimRate=3 ;set to 2 if chars feel weird for u
CVars=a.URO.ForceInterpolation=1